#!/bin/sh
# GPL-2.0-or-later
set -u
BASE=${UPS_NATIVE_BASE:-/volume1/ups-native}
LOG_DIR="$BASE/logs"; MANIFEST_DIR="$BASE/manifests"; BACKUP_DIR="$BASE/backups"; RUNTIME_DIR="$BASE/runtime/nut-2.8.5-3028"; PRIVATE_DRIVER_LINK="$BASE/bin/usbhid-ups"
USB_TABLE=${USB_TABLE:-/usr/lib/udev/devicetable/usb.nut-hid}; SCAN_TABLE=${SCAN_TABLE:-/etc/ups/nutscan-usb.h}; LIVE_CONF=${LIVE_CONF:-/etc/ups/ups.conf}; DEFAULT_CONF=${DEFAULT_CONF:-/etc.defaults/ups/ups.conf}; SYNO_CONF=${SYNO_CONF:-/usr/syno/etc/ups/synoups.conf}; STOCK_DRIVER=${STOCK_DRIVER:-/usr/bin/usbhid-ups}
DROPIN_DIR=${DROPIN_DIR:-/etc/systemd/system/ups-usb.service.d}; DROPIN_FILE=${DROPIN_FILE:-$DROPIN_DIR/20-ups-native-compat.conf}; COMPAT_UNIT=${COMPAT_UNIT:-/etc/systemd/system/ups-native-compat.service}; RC_HOOK=${RC_HOOK:-/usr/local/etc/rc.d/ups-native-compat.sh}
EXPECTED_INITIAL_STOCK_SHA=c40952698fc8b333eba260169328c533f98c4a3dc58174774b0be87b549182c8
log(){ mkdir -p "$LOG_DIR" 2>/dev/null || true; line="$(date '+%Y-%m-%dT%H:%M:%S%z') $*"; printf '%s\n' "$line" >&2; printf '%s\n' "$line" >> "$LOG_DIR/compat.log" 2>/dev/null || true; }
must_root(){ [ "$(id -u)" -eq 0 ] || { echo "ERROR: root required" >&2; exit 1; }; }
get_key(){ /bin/get_key_value "$1" "$2" 2>/dev/null || true; }
dsm_build(){ get_key /etc.defaults/VERSION buildnumber; }; dsm_version(){ get_key /etc.defaults/VERSION productversion; }; dsm_smallfix(){ get_key /etc.defaults/VERSION smallfixnumber; }
build_label(){ printf '%s-%s-u%s' "$(dsm_version)" "$(dsm_build)" "$(dsm_smallfix)"; }
sha(){ sha256sum "$1" | awk '{print $1}'; }
nas_model(){ if [ -r /proc/sys/kernel/syno_hw_version ]; then cat /proc/sys/kernel/syno_hw_version; elif [ -x /usr/syno/bin/synogetkeyvalue ]; then /usr/syno/bin/synogetkeyvalue /etc.defaults/synoinfo.conf upnpmodelname 2>/dev/null || true; fi; }
usb_present(){ for d in /sys/bus/usb/devices/*; do [ -r "$d/idVendor" ] && [ -r "$d/idProduct" ] || continue; v=$(tr 'A-F' 'a-f' < "$d/idVendor"); p=$(tr 'A-F' 'a-f' < "$d/idProduct"); [ "$v:$p" = "09ae:3028" ] && return 0; done; return 1; }
nut_processes(){ ps wwaux 2>/dev/null | grep -E '[u]sbhid-ups|[u]psdrvctl|[u]psd([^a-z]|$)|[u]psmon|[u]pssched' || true; }
verify_private_runtime(){ [ -f "$RUNTIME_DIR/SHA256SUMS" ] || return 1; (cd "$RUNTIME_DIR" && sha256sum -c SHA256SUMS >/dev/null 2>&1); }
set_syno_key(){ key=$1; value=$2; if [ -x /bin/set_key_value ]; then /bin/set_key_value "$SYNO_CONF" "$key" "$value"; return; fi; tmp=$(mktemp); awk -v k="$key" -v v="$value" 'BEGIN{done=0} $0 ~ "^" k "=" {print k "=\"" v "\""; done=1; next} {print} END{if(!done) print k "=\"" v "\""}' "$SYNO_CONF" > "$tmp" && cat "$tmp" > "$SYNO_CONF"; rm -f "$tmp"; }
assert_known_layout(){ for f in "$USB_TABLE" "$SCAN_TABLE" "$LIVE_CONF" "$DEFAULT_CONF" "$SYNO_CONF" "$STOCK_DRIVER"; do [ -e "$f" ] || { log "FAIL: required path missing: $f"; return 1; }; done; [ -x /usr/syno/lib/systemd/scripts/ups-usb.sh ] || { log "FAIL: DSM ups-usb.sh layout not recognized"; return 1; }; systemctl cat ups-usb.service >/dev/null 2>&1 || { log "FAIL: ups-usb.service not found"; return 1; }; grep -qi '0x09ae' "$USB_TABLE" || return 1; grep -qi '0x09ae' "$SCAN_TABLE" || return 1; }
ensure_3028_usb_table(){ if grep -qiE '0x09ae[[:space:]]+0x3028' "$USB_TABLE"; then grep -qiE '^libhidups[[:space:]]+0x0003[[:space:]]+0x09ae[[:space:]]+0x3028' "$USB_TABLE" && return 0; log "FAIL: 09ae:3028 exists in usb.nut-hid with unexpected mapping"; return 1; fi; tmp=$(mktemp); awk '{print; if ($0 ~ /^libhidups[[:space:]]+0x0003[[:space:]]+0x09ae[[:space:]]+0x3024/) { line=$0; sub(/0x3024/,"0x3028",line); print line; found=1 }} END{if(!found) exit 42}' "$USB_TABLE" > "$tmp" || { rm -f "$tmp"; return 1; }; cat "$tmp" > "$USB_TABLE"; rm -f "$tmp"; }
ensure_3028_scan_table(){ if grep -qiE '0x09ae,[[:space:]]*0x3028' "$SCAN_TABLE"; then grep -qiE '0x09ae,[[:space:]]*0x3028,[[:space:]]*"usbhid-ups"' "$SCAN_TABLE" && return 0; log "FAIL: 09ae:3028 exists in nutscan-usb.h with unexpected driver"; return 1; fi; tmp=$(mktemp); awk '{print; if ($0 ~ /0x09ae,[[:space:]]*0x3024,[[:space:]]*"usbhid-ups"/) { line=$0; sub(/0x3024/,"0x3028",line); print line; found=1 }} END{if(!found) exit 42}' "$SCAN_TABLE" > "$tmp" || { rm -f "$tmp"; return 1; }; cat "$tmp" > "$SCAN_TABLE"; rm -f "$tmp"; }
ensure_ups_conf(){ file=$1; tmp=$(mktemp); awk -v path="$BASE/bin" 'BEGIN{inups=0;sawups=0;inserted=0} /^[[:space:]]*driverpath[[:space:]]*=/ {next} /^[[:space:]]*\[ups\][[:space:]]*$/ {if(!sawups){print "driverpath = " path;sawups=1} inups=1;print;next} /^[[:space:]]*\[/ {inups=0} inups && /^[[:space:]]*(vendorid|productid|usb_hid_rep_index|usb_hid_ep_in)[[:space:]]*=/ {next} {print} inups && /^[[:space:]]*port[[:space:]]*=[[:space:]]*auto[[:space:]]*$/ && !inserted {print "\tvendorid = 09ae"; print "\tproductid = 3028"; print "\tusb_hid_rep_index = 1"; print "\tusb_hid_ep_in = 2"; inserted=1} END{if(!sawups||!inserted)exit 43}' "$file" > "$tmp" || { rm -f "$tmp"; return 1; }; cat "$tmp" > "$file"; rm -f "$tmp"; }
snapshot_if_needed(){ label=$(build_label); stock=$(sha "$STOCK_DRIVER"); key="$label-$stock"; manifest="$MANIFEST_DIR/$key.manifest"; [ -f "$manifest" ] && return 0; stamp=$(date +%Y%m%d-%H%M%S); dest="$BACKUP_DIR/$label/$stamp/rootfs"; mkdir -p "$dest" "$MANIFEST_DIR"; files="$USB_TABLE $SCAN_TABLE $LIVE_CONF $DEFAULT_CONF $SYNO_CONF"; for f in $files; do out="$dest$f"; mkdir -p "$(dirname "$out")"; cp -a "$f" "$out"; done; { echo "DSM_VERSION=$(dsm_version)"; echo "DSM_BUILD=$(dsm_build)"; echo "DSM_SMALLFIX=$(dsm_smallfix)"; echo "STOCK_DRIVER_SHA=$stock"; echo "BACKUP_ROOT=$dest"; for f in $files; do echo "ORIGINAL_SHA $f $(sha "$f")"; done; } > "$manifest"; log "Created same-build backup and manifest: $manifest"; }
install_hooks_from_templates(){ mkdir -p "$DROPIN_DIR"; cp -f "$BASE/templates/ups-usb-compat.conf" "$DROPIN_FILE"; cp -f "$BASE/templates/ups-native-compat.service" "$COMPAT_UNIT"; cp -f "$BASE/templates/ups-native-compat-rc.sh" "$RC_HOOK"; chmod 0755 "$RC_HOOK"; systemctl daemon-reload; systemctl enable ups-native-compat.service >/dev/null 2>&1 || true; }
